### ISSUE TITLE
About function "read_files" in rvtt_fixed_threshold.py

### ISSUE THREAD

**Issue by Renown-TAL** [snz20/RVTT#1]
Hi, I note you define "mafs" in this function to filter rare variants by cutoff, but not return the fitler dataframe. Beside, the "h_maf" is define before used(may define by "h_maf = sorted(list(set(mafs)))", but you make it note), could you correct the function? thanks

**Comment by snz20** [comment]
Hi, in the rvtt_fixed_threshold version, the read_files function is not intended to do any MAF filtering on the dataframe. It just returns the dataframe with all variants in the genes of interest. The create_indiv_count_matrix function takes care of the minor allele frequency filtering (See, df_sel = df.loc[df['PopMAF'] <= cutoff]). I have removed the extraneous lines from the read_files that were creating confusion. Thanks!
