### ISSUE TITLE
RVTT_preprocess_gzvcf gave no output

### ISSUE THREAD

**Issue by pushpinder-bu** [snz20/RVTT#2]
Hi,
I am new to SNP and rare variant analysis. I came across your paper and was trying to run my sample through it.
I annotated the variant using SnpEff and SnpSift as recommend, but while running the preprocessing step I get no results in my output. I checked the vcf file and it does have variants which fall under the "incl" mentioned in your preprocessing script.
Can you suggest what can be going wrong here?

**Comment by snz20** [comment]
Hi, can you paste the INFO field of a coding locus from your VCF file here, please? It is most likely a formatting issue.

**Comment by pushpinder-bu** [comment]
[header.txt](https://github.com/snz20/RVTT/files/14185237/header.txt)
Header file from the VCF.

**Comment by snz20** [comment]
I have added some diagnostic code to the preprocess_gzvcf.py file. It should now print a dictionary at completion showing how many loci per included categories goes to the output file. 
Please check the following in your input files:
1. In your tab-separated fam file case/control labels are correct (case:2, control:1). If cases and controls do not have mutations at a locus, that will not be included in the output.
2. Here is a sample vcf.gz and fam file you can test with. 
[testsamples_filt.vcf.gz](https://github.com/snz20/RVTT/files/14186945/testsamples_filt.vcf.gz)
[testsamples.fam.txt](https://github.com/snz20/RVTT/files/14186948/testsamples.fam.txt)
